export const carNames = [
  'Shelby GT500CR',
  'Bentley EXP 100 GT',
  'Bugatti Chiron',
  'Jaguar XJS',
  'Chevrolet Camaro',
  'Lotus Esprit',
  'Ford GT',
  'Cadillac',
  'Bugatti Type 57',
  'Noble M12 M400',
  'Dodge Viper',
  'Mercedes-Benz 540K',
  'Ford Boss 302 Mustang',
  'Volvo P1800',
  'Volkswagen Karmann Ghia',
  'Ferrari 360 Modena',
  'Nissan GT-R',
  'Chevrolet Corvette',
  'Alfa Romeo Spider',
  'Porsche Carrera GT',
  'Lamborghini Diablo',
  'Hudson Hornet',
  'Ford Thunderbird',
  'DeLorean DMC',
  'Lamborghini Reventon',
  'Austin-Healey 3000',
  'BMW M1',
  'Honda S2000',
  'Lotus Elise',
  'Ferrari F40',
  'SS Cars SS100',
  'Triumph Spitfire',
  'BMW Z8',
  'Talbot-Lago T150 CSS',
  'Porsche 918 Spyder',
  'Lincoln Continental',
  'Alfa Romeo 4C',
  'Nissan Fairlady Z',
  'Ferrari Testarossa',
  'Triumph TR6',
  'Lexus LFA',
  'Morgan Plus 4',
  'Lamborghini Huracan',
  'Aston Martin DB6',
  'Lotus Elite',
  'Lamborghini Aventador',
  'BMW 3.0CSL',
  'Porsche 356',
  'Mazda RX7',
  'Ferrari F50',
  'Tesla Model S',
  'Koenigsegg Agera',
  'Audi R8',
  'Bugatti Veyron',
  'Ferrari Enzo',
  'BMW M6',
  'McLaren P1',
  'Ferrari LaFerrari',
];
